apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app-service
spec:
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
      - name: bank-app-service
        image: dhillevajja/bankapp:1.0
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 250m
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://root:Test@123.bankappdb-0.bankappdb-svc:3306/bankappdb?useSSL=false&serverTimezone=UTC
        
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-svc
spec:
  type: NodePort
  selector:
    app: bank-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32500
